name: Build Multi-Architecture Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag'
        required: false
        default: 'latest'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build AMD64 image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: false
        tags: bluespice-search:${{ inputs.tag }}-amd64
        outputs: type=docker,dest=/tmp/bluespice-search-amd64.tar
        
    - name: Build ARM64 image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/arm64
        push: false
        tags: bluespice-search:${{ inputs.tag }}-arm64
        outputs: type=docker,dest=/tmp/bluespice-search-arm64.tar

    - name: Compress AMD64 image
      run: gzip /tmp/bluespice-search-amd64.tar
        
    - name: Compress ARM64 image
      run: gzip /tmp/bluespice-search-arm64.tar
        
    - name: Upload AMD64 image artifact
      uses: actions/upload-artifact@v4
      with:
        name: bluespice-search-amd64-${{ inputs.tag }}
        path: /tmp/bluespice-search-amd64.tar.gz
        retention-days: 30
        
    - name: Upload ARM64 image artifact
      uses: actions/upload-artifact@v4
      with:
        name: bluespice-search-arm64-${{ inputs.tag }}
        path: /tmp/bluespice-search-arm64.tar.gz
        retention-days: 30
